Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 53

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Style/NumericLiterals:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile
